# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set pnpm settings
        run: echo "npm_config_auto_install_peers=true" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 18
          run_install: true
      - run: pnpm install 
      - run: pnpm build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
